name: Scout - image cves

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    strategy:
      fail-fast: true
      matrix:
        include:
          - dockerfile: ./deploy/api.dockerfile
            image_name: avatars_api
            image_tag: latest
          - dockerfile: ./deploy/web.dockerfile
            image_name: avatars_web
            image_tag: latest
    steps:
      - 
        # Login to Docker Hub
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        # Analyze image for critical and high CVEs
        name: Analyze image for critical and high CVEs
        id: docker-scout-cves
        if: ${{ github.event_name != 'pull_request_target' }}
        uses: docker/scout-action@v1
        with:
          command: cves
          image: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image_name }}:${{ matrix.image_tag }}
          sarif-file: sarif.output.json
          summary: true
      # - 
      #   # Upload CVEs (SARIF) result
      #   name: Upload CVEs (SARIF) result
      #   id: upload-sarif
      #   if: ${{ github.event_name != 'pull_request_target' }}
      #   uses: github/codeql-action/upload-sarif@v3
      #   with:
      #     sarif_file: sarif.output.json