name: Build - docker build cloud

on:
  push:

env:
  REGISTRY: docker.io

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    strategy:
      fail-fast: true
      matrix:
        include:
          - dockerfile: ./deploy/api.dockerfile
            image_name: avatars_api
            image_tag: latest
          - dockerfile: ./deploy/web.dockerfile
            image_name: avatars_web
            image_tag: latest
    steps:
      -
        # Check out code
        name: Check out code
        uses: actions/checkout@v3
      -
        # Login to Docker Hub
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        # Set up QEMU
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        # Set up Docker Buildx
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: cloud
          endpoint: "demonstrationorg/default"
          install: true
      -
        # Build and push
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image_name }}:${{ matrix.image_tag }}
          push: true