name: Test - testcontainers cloud

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - 
        # Check out code
        name: Check out code
        uses: actions/checkout@v3
      - 
        # Setup python
        name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - 
        # Install dependencies for python tests
        name: Install dependencies
        run: pip install pytest testcontainers psycopg
      - 
        # Start Testcontainers Cloud session
        name: Start Testcontainers Cloud session
        uses: atomicjar/testcontainers-cloud-setup-action@v1
        with:
          token: ${{ secrets.TC_CLOUD_TOKEN }}
      - 
        # Run python tests (testcontainers)
        name: Run tests
        run: pytest ./tests
      - 
        # (Optional) Stop Testcontainers Cloud session
        name: Stop Testcontainers Cloud session
        uses: atomicjar/testcontainers-cloud-setup-action@v1
        with:
          action: terminate